<?php
/**
 * UrbanEats Phase 8: Cleanup Duplicate Test Restaurants & Accounts
 */
require_once __DIR__ . '/config/db.php';
header('Content-Type: application/json');

$pdo = getDBConnection();

// 1. Delete duplicate test restaurants created by automated test runs
$delRestStmt = $pdo->prepare("
    DELETE FROM restaurants 
    WHERE name LIKE 'Pending Taste Buka%' OR slug LIKE '%ending-aste-uka%' OR id > 4
");
$delRestStmt->execute();
$deletedRestCount = $delRestStmt->rowCount();

// 2. Delete test vendor & rider applicant accounts generated by automated test runs
$delUsersStmt = $pdo->prepare("
    DELETE FROM users 
    WHERE email LIKE 'vendor_applicant_%' OR email LIKE 'rider_applicant_%' OR email LIKE 'cust_rider_test_%' OR email LIKE 'customer_v5_%'
");
$delUsersStmt->execute();
$deletedUsersCount = $delUsersStmt->rowCount();

// 3. Select remaining clean restaurants
$resStmt = $pdo->query("SELECT id, owner_id, name, slug, status, is_active FROM restaurants ORDER BY id ASC");
$cleanRestaurants = $resStmt->fetchAll();

echo json_encode([
    'status'                => 'success',
    'deleted_restaurants'   => $deletedRestCount,
    'deleted_test_accounts' => $deletedUsersCount,
    'clean_restaurants'     => $cleanRestaurants
], JSON_PRETTY_PRINT);
